index:
   path: /
   controller: App\Controller\MenuItemController

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

login:
    path: /login
    controller: App\Controller\LoginController::form

memberSpace: 
    path: /memberSpace
    controller: App\Controller\MemberSpaceController

rendezVous:
    path: /rendezVous
    controller: App\Controller\RendezVousController

# renvezVous:
#     path: /rendezVous/{appointment}
#     controller: App\Controller\RendezVousController

contact:
    path: /contact
    controller: App\Controller\ContactController

# app_menu_item:
#     path: /menu
#     controller: App\Controller\MenuItemController