index:
   path: /
   controller: App\Controller\MenuItemController

login:
    path: /login
    controller: App\Controller\LoginController::form

memberSpace: 
    path: /memberSpace
    controller: App\Controller\MemberSpaceController

rendezVous:
    path: /rendezVous
    controller: App\Controller\RendezVousController
    
toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"

contact:
    path: /contact
    controller: App\Controller\ContactController

mentionlegale:
    path: /mentionlegale
    controller: App\Controller\MentionLegaleController

prestation:
    path: /prestation
    controller: App\Controller\PrestationController

article:
    path: /article
    controller: App\Controller\ArticleController

galerie:
    path: /galerie
    controller: App\Controller\GalerieController

# app_menu_item:
#     path: /menu
#     controller: App\Controller\MenuItemController


# renvezVous:
#     path: /rendezVous/{appointment}
#     controller: App\Controller\RendezVousController